server:
  port: 7876

spring:
  application:
    name: discover-client

eureka:
  # Eureka? ??? ??? ?????.
  client:
    # ?? ??????? Eureka ??? ???? ??? ?????.
    register-with-eureka: true
    # Eureka ???? ??? ??? ???? ??? ?????.
    fetch-registry: true
    # Eureka ??? URL? ?????.
    service-url:
      # Eureka ??? ?? ??? ?????.
      defaultZone: http://localhost:8761/eureka

  # HeaderBeat ?? ??
  instance:
    lease-renewal-interval-in-seconds: 5   # Heartbeat ?? (???: 30?)
    lease-expiration-duration-in-seconds: 10 # Heartbeat ?? ? ???? ??? ?? (???: 90?)