server:
  port: 7876

spring:
  application:
    name: discover-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:

      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://localhost:8762/eureka, http://localhost:8763/eureka

  instance:
    lease-renewal-interval-in-seconds: 5   # Heartbeat ?? (???: 30?)
    lease-expiration-duration-in-seconds: 10 # Heartbeat ?? ? ???? ??? ?? (???: 90?)