server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  # Eureka instance 관련된 설정을 정의합니다.
  instance: 
    # instance-id 설정
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Heartbeat 설정
    #lease-renewal-interval-in-seconds: 5   # Heartbeat 주기 (기본값: 30초)
    #lease-expiration-duration-in-seconds: 10 # Heartbeat 없을 때 제거까지 걸리는 시간 (기본값: 90초)

  # Eureka client 관련된 설정을 정의합니다.
  client:
    # 현재 애플리케이션을 Eureka 서버에 등록할지 여부를 설정합니다.
    register-with-eureka: true
    # Eureka 서버에서 서비스 정보를 가져올지 여부를 설정합니다.
    fetch-registry: true
    # Eureka 서버의 URL을 설정합니다.
    service-url:
      # Eureka 서버의 기본 주소를 설정합니다.
      defaultZone: http://127.0.0.1:8761/eureka

