############################################################
# ConfigMap은 설정 정보를 key-value 형태로 저장하기 위한 Kubernetes #
# 보통 애플리케이션의 환경 설정 파일이나 환경 변수로 사용                #
###########################################################

apiVersion: v1               # API 버전 (ConfigMap은 항상 v1 사용)
kind: ConfigMap              # 리소스 종류 지정 ConfigMap
metadata:
  name: my-config            # ConfigMap의 이름 (필수)
  namespace: default         # 네임스페이스 (생략 시 default) -  클러스터 내에서 리소스를 논리적으로 분리하여 더 잘 관리하고, 보안, 자원 제한, 협업을 가능하게 해주는 핵심 기능

# 아래의 data 항목은 설정 값을 key-value 형태로 저장
# 각 key는 환경 변수명이나 파일명으로 사용 가능
data:
  # key: 값 형태로 지정
  gateway_ip: "192.168.65.3"
  token_expiration-time: "86400000"
  token_secret: "asd123asdkz9xc8v123klxzc890234kljasd8213sd8k8s"
  order-service-url: "http://order-service:10000"
  bootstrap-servers: "192.168.65.3:9092"

