services:
  config-service:
    build:
      context: ../config-service
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - micro-service-network

  discover-service:
    build:
      context: ../discovery-service
    container_name: discover-service
    ports:
      - "8761:8761"
    networks:
      - micro-service-network
    depends_on:
      - config-service

  api-gateway-service:
    build:
      context: ../api-gateway/gateway-server
    container_name: api-gateway-service
    ports:
      - "8000:8000"
    networks:
      - micro-service-network
    environment:
      - "spring.cloud.config.uri=http://config-service:8888"
      - "spring.rabbitmq.host=rabbitmq"
      - "eureka.client.serviceUrl.defaultZone=http://discover-service:8761/eureka/"
    depends_on:
      - config-service
      - discover-service
      - rabbitmq

  user-service:
    build:
      context: ../user-service
    container_name: user-service
    networks:
      - micro-service-network
    environment:
      - "spring.profiles.active=prod"
      - "spring.cloud.config.uri=http://config-service:8888"
      - "spring.rabbitmq.host=rabbitmq"
      - "eureka.client.serviceUrl.defaultZone=http://discover-service:8761/eureka/"
      - "management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans"
    depends_on:
      - api-gateway-service

  rabbitmq:
    image: rabbitmq:3.12-management  # 관리 UI 포함된 버전
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP 프로토콜 포트
      - "15672:15672"  # 웹 UI 포트
      - "4369:4369"    # 클러스터링 포트
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq-volume:/var/lib/rabbitmq  # 현재 디렉토리의 `data` 폴더를 마운트
    networks:
      - micro-service-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "mydb"
    volumes:
      - ./mariadb-volume:/var/lib/mysql
    networks:
      - micro-service-network

networks:
  micro-service-network:
    #driver: bridge
    # ✅ "docker network create micro-service-network" 명령어를 통해 network를 생성
    #     - 서로 다른 docker-compose.yml을 연결하여 사용하기 위함
    external: true  # 이미 생성된 네트워크 사용