server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Global Filter Setting - only used to yml
#            preLogger: true
#            postLogger: true
      routes:
        - id: first-service
          uri: lb://YOO-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: second-service
          uri: lb://YOO-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            # args를 적용하기 위햐서는 "name:"을 사용해줘야 함
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi~~~~ Logging Filter Setting - using yml
                preLogger: true
                postLogger: true
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          # POST - login 요청이 들어 욜 경우
          predicates:
            - Path=/user-service/login
            - Method=POST
          # Cookie 삭제 및 user-service 제거
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**

# jwt setting
token:
  secret: asd123asdkz9xc8v123klxzc890234kljasd8213sd8


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
