server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Global Filter Setting - only used to yml
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: http://localhost:8081
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/**
          filters:
            # args를 적용하기 위햐서는 "name:"을 사용해줘야 함
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi~~~~ Logging Filter Setting - using yml
                preLogger: true
                postLogger: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://localhost:8761/eureka/
