spring:

  # RabbitMQ Setting
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  # Config Server Setting
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      name: user-service  # `user-service.yml`을 읽도록 설정

  # h2 접근 설절
  h2:
    console:
      # H2 콘솔 활성화 여부 (기본값: false)
      enabled: true
      settings:
        # 외부에서 H2 콘솔 접속을 허용할지 여부 (보안상 주의 필요)
        web-allow-others: true
      # H2 콘솔 접속 URL 설정 (예: http://localhost:8080/h2-console)
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시 DB 초기화 방식
    show-sql: true  # SQL 실행문 로깅

# Eureka 설정
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # lease-renewal-interval-in-seconds: 5   # Heartbeat 주기 (기본값: 30초)
    # lease-expiration-duration-in-seconds: 10 # Heartbeat가 중단되었을 때 인스턴스를 제거하는 시간 (기본값: 90초)

  # Eureka client 설정 (Eureka 서버에 등록할지 여부)
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discover-service:8761/eureka

greeting:
  message: This is Micro User Service!!

management:
  # Zipkin 설정
  tracing:
    sampling:
      probability: 1.0 # 샘플링할 비율 - 100% 샘플링 (모든 요청을 추적)
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # Zipkin 서버 주소

# FeignClient Log 설정
logging:
  level:
    com.yoo.user_service.feignClient: DEBUG