server:
  port: 0

spring:
  application:
    name: user-service

  profiles:
    active: local

management:
  # Actuator 설정
  endpoints:
    web:
      exposure:
        # /actuator/** 로 사용할 기능 설정
        include: refresh, health, beans, busrefresh, circuitbreakers, info, metrics, prometheus
