server:
  port: 8761

spring:
  application:
    name: discoveryservice

# ℹ️ eurek 설정 - Discovery Server 이기에 자기 자신을 등록할 필요가 없기에 false 처리 ( 기본 값 : true )
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
# ✅ Docker를 사용한 테스트 진행
spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:8763/eureka
  instance:
    hostname: zero

---
spring:
  config:
    activate:
      on-profile: eureka3

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3:8762/eureka
  instance:
    hostname: one