server:
  port: 8888 # Config Server Default Port Number

spring:
  profiles:
    active: local
  application:
    name: config-service

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        # /actuator/** 로 사용할 기능 설정
        include: health, busrefresh, metrics, prometheus



