spring:
  # RabbitMQ Setting
  rabbitmq:
    host: localhost
    port: 5672
    username : admin
    password: admin
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/yoo/Desktop/Project/config-repo [ local repository ]
          uri: https://github.com/edel1212/config-repo.git


## ✨ 대칭키 방식
#encrypt:
#  key: abcdefghijklmnopqrstuvwxyz0123456789

## ✨ 비대칭키 방식
encrypt:
  key-store:
    location: file://${user.home}/Desktop/Project/keystroe/apiEncryptionKey.jks
    password: 123456
    alias: apiEncryptionKey


#################
## native 설정 ###
#################
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///Users/yoo/Desktop/Project/Micro-Service-Architecture-Study/native-file-repo

