server:
  port: 8888 # Config Server Default Port Number

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/yoo/Desktop/Project/Micro-Service-Architecture-Study/git-local-repo
          search-paths: .  # ?? ?????? ??
          default-label: main  # ?? ??? ?? (?? Git ????? ?? ??)

