spring:
  # RabbitMQ Setting
  rabbitmq:
    host: localhost
    port: 5672
    username : admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edel1212/config-repo.git

## ✨ 비대칭키 방식
encrypt:
  key-store:
    # ✅ 해당 apiEncryptionKey.jks 파일은 DockerFile 생성 시 /app Directory로 카피했음
    location: file:///app/apiEncryptionKey.jks
    password: 123456
    alias: apiEncryptionKey



